#!/usr/bin/env python3
# Copyright 2025 Canonical Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Mock `gh` CLI for integration tests.

Place the directory containing this script at the front of PATH:

    export PATH="$SPREAD_PATH/tests/spread/lib/mock-gh-bin:$PATH"

The mock responds to the `gh` subcommands that update_issue.py uses:

    gh issue view <number> --json body
    gh issue view <number> --json assignees
    gh issue view <number> --json comments
    gh issue edit <number> ...
    gh issue comment <number> ...

Behaviour is controlled by environment variables:

    MOCK_GH_ISSUE_BODY  Markdown body returned by `gh issue view --json body`.
    MOCK_GH_COMMENTS    JSON array of comments (default: []).
    MOCK_GH_LOG         File to append commands to (for assertions).
"""

from __future__ import annotations

import json
import os
import sys


def log(argv: list[str]) -> None:
    log_path = os.environ.get('MOCK_GH_LOG')
    if not log_path:
        return
    with open(log_path, 'a', encoding='utf-8') as f:
        f.write('gh ' + ' '.join(argv) + '\n')


def handle_view(args: list[str]) -> None:
    # args: <number> [--json <field> ...]
    if len(args) < 3 or args[1] != '--json':
        return
    field = args[2]
    if field == 'body':
        body = os.environ.get('MOCK_GH_ISSUE_BODY', 'No body')
        print(json.dumps({'body': body}))
    elif field == 'assignees':
        print(json.dumps({'assignees': []}))
    elif field == 'comments':
        comments = json.loads(os.environ.get('MOCK_GH_COMMENTS', '[]'))
        print(json.dumps({'comments': comments}))
    else:
        print('{}')


def main(argv: list[str]) -> int:
    log(argv)
    if not argv or argv[0] != 'issue':
        sys.stderr.write(f'mock-gh: unknown command: {argv[0] if argv else ""}\n')
        return 1
    sub = argv[1] if len(argv) > 1 else ''
    rest = argv[2:]
    if sub == 'view':
        handle_view(rest)
    elif sub in ('edit', 'comment'):
        pass
    else:
        sys.stderr.write(f'mock-gh: unknown issue subcommand: {sub}\n')
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
