name: Review Listing Request

on:
  issues:
    types: [opened, labeled]
  issue_comment:
    types: [created, edited]

permissions: {}

jobs:
  review-listing-request:
    if: contains(github.event.label.name, 'listing-request')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Checkout operator
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # This is used to extract the best practices from the docs.
      - name: Checkout charmcraft
        uses: actions/checkout@v4
        with:
          repository: canonical/charmcraft
          path: charmcraft
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba  # v6.3.1

      - name: Update issue summary and description
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            uvx python update_issue.py --issue-number "${{ github.event.issue.number }}"
