name: Review Listing Request

on:
  issues:
    types: [opened, labeled]

permissions: {}

jobs:
  review-listing-request:
    if: contains(github.event.label.name, 'listing-request')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Checkout operator
        uses: actions/checkout@v4
        with:
          repository: canonical/operator
          path: operator
          persist-credentials: false

      - name: Checkout charmcraft
        uses: actions/checkout@v4
        with:
          repository: canonical/charmcraft
          path: charmcraft
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install uv
        uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba  # v6.3.1

      # TODO: If we update the description then the reporter can edit it, which means they could
      # cheat and tick boxes. Perhaps this should be a comment instead? I think the reporter can't
      # then edit comments, unless they are have rights on this repository, which should mean that
      # they are trustworthy.
      - name: Update issue summary and description
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            uvx python update_issue.py --issue-number "${{ github.event.issue.number }}"
